name: attendance
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  file_picker: ^5.3.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0

  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.1
  gap: ^3.0.0
  get: 4.6.5
  open_file: ^3.3.1
  path_provider: ^2.0.15
  pdf: ^3.1.0
  permission_handler: ^10.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
